# .gitlab-ci.yml
windows-build:
  tags:
    - windows
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt pyinstaller
    - pyinstaller --onefile --windowed --add-data "sounds/*;sounds/" --add-data "config.json;." main.py
  artifacts:
    paths:
      - dist/*.exe
